### ISSUE TITLE
Define complete subset of similarity measures

### ISSUE THREAD

**Issue by pierretoussing** [Climate-Data-Science/Climate-Similarity-Metrics#21]
Which similarity measures should be used in order to cover all the problems we want to solve and all the properties similarity measures can have?

- [x] Read the section about similarity measures in [this paper](https://dbis.ipd.kit.edu/download/clustagg_InformationTechnology_CR.pdf) and inspect if their categorization makes sense for our project.

- [x] Define all the problems we want to solve with different similarity measures: Different value ranges, negative values, different value distributions, inverted value ranges,...

- [x] Add value ranges to similarity measures summary

- [x] Define a complete subset of similarity measures

**Comment by pierretoussing** [comment]
@pawelbielski 
I read the section in the paper linked above and I think we should stick with our idea of defining the problems and then select a subset of similarity measures which cover all this problems.

**Comment by pierretoussing** [comment]
Problems of different similarity measures:

- Negative values (i.e. Pearson's Correlation)

- Different value distributions (i.e. Mutual Information)

- Different value ranges (i.e. Manhattan Distance/Euclidean Distance)

- Inverted value ranges (i.e. Transfer Entropy)

**Comment by pawelbielski** [comment]
@pierretoussing I agree, that we should start with these 4 problems that similarity measures different than Pearson have. Then for every of the defined problems we give an example measure, and propose solution/solutions.
