### ISSUE TITLE
Attach meaning to combination

### ISSUE THREAD

**Issue by pierretoussing** [Climate-Data-Science/Climate-Similarity-Metrics#22]
The focus of this work lies on the combination-step. Different possibilities to extend this step can be taken into account. Create a module for each one of this extensions:

- [x] No dependencies: Create a module to show areas of no dependencies

- [x] Power of dependency: Take away sign of Pearson's Correlation when we are only interested in power of dependency. Combine the absolute values of similarity measures with Pearson's

- [x] Meaningful dependencies: Take sign of Pearson's and derive value from other similarity measure or from combination of Pearson's with the other similarity measures, because Pearson's already gives us the direction of the dependency

**Comment by pierretoussing** [comment]
The `No dependencies: Create a module to show areas of no dependencies` will eventually become unnecessary when the module of agreement between similarity measures #20 is implemented.

**Comment by pawelbielski** [comment]
I am not sure if the `No dependencies: Create a module to show areas of no dependencies` is unnecessary. Could you maybe put the results into the presentation? All that you have implemented has potential to be very powerful and important.
