### ISSUE TITLE
Compute time delayed dependencies

### ISSUE THREAD

**Issue by pierretoussing** [Climate-Data-Science/Climate-Similarity-Metrics#24]
Another possibility is to look for dependencies over time. 

- [x] Write a function that computes the similarity of the reference series to the data shifted by a given amount of time. It takes in a list of  integers that indicate how much to shift the data. The output is a plot with the similarity maps for each time shift in one column.

- [x] Look at the nature paper for relevant time shifts (1 month, 3 months, 12 months,...)

**Comment by pierretoussing** [comment]
In the nature paper, they used the following time shifts:

- 1-2 months

- 2-4 months

- 4-8 months

- 8-16 months

- 16-32 months

- 32-64 months

- 64-128 months

**Comment by pawelbielski** [comment]
@pierretoussing What is the interpretation of the delay ranges, e.g. 1-2, 2-4? Does it make sense in our case to define delay in that way?

**Comment by pierretoussing** [comment]
@pawelbielski The delay ranges in the nature paper mean that they used all of this delays for the similarity computation e.g 2-4 means they used the delays 2, 3, and 4 for this one map. This has something to do with the similarity measures they used: Wavelet multi-scale correlation. This measure is designed for such this purpose. 
Using standard similarity measures, we would then have to define a method to combine the similarity values for 2, 3 and 4 months in order to combine them into one value for the delay range 2-4 months.
So using standard similarity measures (and also implementing the approach Peter suggested), we define the time delays as a simple integer and then shift the whole map by this delay.
I used 1, 3 and 12 months as delays. It means that the similarity is computed between the actual reference series and the whole map shifted by the respective time delay. I used the mean as fill value to assure the time series still have the same length (to avoid problems with similarity calculations).
This delays act as example, I don't know if they are meaningful or if we should use other delays? I thought that the climate scientists would provide us with the delays they want to look at.

**Comment by pierretoussing** [comment]
Peter suggested that it would be better to drop points in order to keep the length of the time series equal, than filling up with the mean.

- [ ] Modify the compute_time_delayed_dependencies so it drops points and does not fill up.
