### ISSUE TITLE
Similarities over time and levels

### ISSUE THREAD

**Issue by pierretoussing** [Climate-Data-Science/Climate-Similarity-Metrics#26]
- [x] Create a function that computes and plots the similarities of a reference series to list of datasets (i.e. containing different levels of the u wind component) for different delays of time (1 month, 3 month, 12 months)

**Comment by pawelbielski** [comment]
@pierretoussing Does the solution work with the agreeableness measure? Could you demonstrate it? Last time we discussed that the agreeableness is what is very helpful for the interpretation of plots.

**Comment by pierretoussing** [comment]
@pawelbielski I can make it work with the agreeableness measures. But not with splitting into the 3 maps like we did it before (high values, low values, rest), because I already have 2 dimensions e.g. level and time, so splitting each map into 3 maps would require a 3 dimensional plot or it would result in something very chaotic.
I will implement a prototype for the agreeableness over time and levels where we don't split into these 3 maps mentioned befored and then we can look how to improve it.

**Comment by pierretoussing** [comment]
As the current approach for plotting the agreeableness is not very clear, we decided to plot it in another way.
Implement the following functions:
- [ ] Plot maps where the measures agree the values are high
1. Compute similarity with each measure
2. Combine the maps into one map containing the mean of the values
3. Combine the maps from 1 into one map containing the agreement of the values using an agreeableness measure (e.g. std, entropy,...)
4. Filter the maps using thresholds (one threshold for the mean values and one threshold for the agreement) and plot the remaining points in one color (e.g. blue)
5. Repeat step 4 with different thresholds
6. Plot all combinations of thresholds in a matrix

- [ ] Plot maps where the measures agree the values are low (same process ass above)
