### ISSUE TITLE
Find similarity metrics that could be useful for climate data

### ISSUE THREAD

**Issue by pawelbielski** [Climate-Data-Science/Climate-Similarity-Metrics#5]
Apart from Pearson's correlation and Mutual Information, there exist other similarity metrics that could be useful in our case. You can take the [Nature paper](https://www.nature.com/articles/s41598-019-45423-5.pdf) that you already read as a starting point. The authors present a list of potentially useful similarity metrics there.

You may use the Google Scholar for finding more similarity metrics.
<img width="719" alt="Searching_for_papers" src="https://user-images.githubusercontent.com/15989174/80371706-9c790100-8892-11ea-9035-553a9d35393e.PNG">

Steps:

- [x] Perform 1st pass of possibly many papers (you may start from the nature paper)

- [x] Perform 2nd pass for the most relevant papers.

- [x] Check if a python implementation is available.

- [x] Check if python libraries implementing a concrete simialarity metric do not have any other similarity metrics in the same package.

- [x] Write a summary of all useful similarity metrics that we could use for this project, together with the information about available code implementation.

**Comment by pawelbielski** [comment]
Great work so far! @pierretoussing Keep reading and summarizing papers that you find relevant. Starting with the papers that you marked as _References I would like to follow_ from your previous summaries might be a good starting point. You can also use the google scholar approach described above. At some point, after our meeting with climate scientists we will discuss ideas from the Data Science/ Computer Science/ IPD Boehm Chair perspective. Your summaries will help find the right story for your Thesis before presenting the proposal.

**Comment by pierretoussing** [comment]
@pawelbielski 
I went through the literature and maybe discovered another interesting approach: Converting the time series to symbol sequences using SAX (Symbolic Aggregate Approximation) and then applying a sequence similarity metric like Levenshtein distance, Hamming distance,  biggest common subsequence,...

**Comment by pawelbielski** [comment]
@pierretoussing 
Symbolic similarity metrics indeed are worth trying out (but not as the first priority).

In order to find more meaningful metrics you can try the [Snowballing approach](https://dl.acm.org/doi/10.1145/2601248.2601268) of finding related papers.

**Comment by pawelbielski** [comment]
In "Related Work" of the [PhD Thesis](https://d-nb.info/1205001891/34) of our former colleague from Institute you can find some interesting state of the art dependency/similarity metrics.

**Comment by pierretoussing** [comment]
This issue will be continued in #17
